### ISSUE TITLE
Fix YAML parsing of notifications/pop-up

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/ai4-dashboard#186]
The notifications (parsed from the [status repo](https://github.com/AI4EOSC/status)) will fail to display if comments are present, even if they are valid YAML syntax.
We have to parse the string with a YAML parser.

Issue example:
```yaml
title:  Cluster maintenance
summary:  Around the 12th of September we scheduled a maintenance downtime for IFCA datacenters. Please make sure to backup your deployments to avoid losing data. 
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2024-08-20T00:00:00.000Z  # start date when the notification will appear
end: 2024-09-15T00:00:00.000Z  # end date when the notification will disappear
```

Also, related to this, the popup is showing the issue name not the real YAML information (title+description)
![image](https://github.com/user-attachments/assets/767b7c3e-b726-40ee-ad2e-25ab5f5cab54)
https://github.com/AI4EOSC/status/issues/242

```yaml
title:  ⚠️ Maintenance downtime is close! 
summary:  We have scheduled a maintenance downtime for Sept. 12th. Please backup your deployments to avoid losing data! 
vo:
start: 2024-09-05T00:00:00.000Z
end: 2024-09-15T00:00:00.000Z
```
